apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data02
  name: data02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
status: {}
