apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data03
  name: data03
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
status: {}
